name: kkfn test

#on: [push]

# 在master分支发生push事件时触发。
on: 
  push:
    branches:
      - master

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v2 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      # - name: Use Node.js ${{ matrix.node-version }} # 步骤2
      #   uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          # node-version: ${{ matrix.node-version }} # 版本
          persist-credentials:false
      
          # 生成静态文件
      - name: Build
        run: npm install && npm run deploy

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
          BRANCH: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
          BASE_BRANCH: master # 要部署的文件夹所在的分支.
          FOLDER: docs/.vuepress/dist # vuepress 生成的静态文件存放的地方